import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { analyze } from '../analyze.js';
import { roslynClasses } from '../roslyn.js';
import { reviewProposal } from '../review.js';
import { applyProposal, propose, saveProposal } from '../convert.js';
import { sha256, writeJson } from '../util.js';
import { currentFindings, findingId, resolveFinding, resolutions } from '../findings.js';

const fixture = path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../fixtures/SampleMaui');
const behaviorFixture = path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../fixtures/BehaviorMaui');
test('Roslyn and XAML analysis finds pages, routes, bindings, classes',async () => {
  const model=await analyze(path.join(fixture,'SampleMaui.sln'));
  assert.equal(model.pages.length,1);
  assert.equal(model.pages[0].route,'home');
  assert.deepEqual(model.pages[0].bindings,['Customers','Query']);
  assert.deepEqual(model.pages[0].commands,['SearchCommand']);
  assert.equal(model.pages[0].viewModel,'MainPageViewModel');
  assert.equal(model.analysisMode,'semantic');
  assert.equal(model.classes.find(c=>c.name==='MainPageViewModel')?.properties.find(p=>p.name==='Query')?.type,'string');
  assert.ok(model.classes.some(c=>c.name==='MainPageViewModel'&&c.navigation.length===1));
  assert.equal(model.coverage.services,1);
});
test('semantic extraction recognizes generated properties, commands, and stable list keys',async()=>{
  const root=await mkdtemp(path.join(os.tmpdir(),'maui2rn-roslyn-'));
  await writeFile(path.join(root,'Demo.cs'),`using System.Collections.Generic;
class Customer { public int Id { get; set; } }
class DemoViewModel {
  [ObservableProperty] private string query = "";
  public List<Customer> Customers { get; set; } = new();
  [RelayCommand] public void Open() { Shell.Current.GoToAsync("home"); }
  [RelayCommand] public void Set() { Query = "123"; }
}`);
  const result=await roslynClasses(root);
  const vm=result.classes.find(c=>c.name==='DemoViewModel');
  assert.equal(result.analysisMode,'semantic');
  assert.ok(vm?.properties.some(p=>p.name==='Query'&&p.sourceKind==='observableField'));
  assert.equal(vm?.properties.find(p=>p.name==='Customers')?.itemKey,'Id');
  assert.deepEqual(vm?.commands?.[0]?.actions,[{kind:'navigate',target:'',value:'home',valueType:'route'}]);
  assert.equal(vm?.commands?.[0]?.supported,true);
  assert.deepEqual(vm?.commands?.find(c=>c.name==='SetCommand')?.actions,[{kind:'set',target:'Query',value:'123',valueType:'string'}]);
});
test('behavior fixture maps navigation, validation, HTTP, and native integration review',async()=>{
  const model=await analyze(behaviorFixture);
  assert.equal(model.pages.length,2);
  assert.equal(model.pages.find(p=>p.id==='MainPage')?.viewModel,'MainPageViewModel');
  assert.ok(!model.findings.some(f=>f.code==='BINDING_UNRESOLVED'||f.code==='COMMAND_UNRESOLVED'));
  const root=await mkdtemp(path.join(os.tmpdir(),'maui2rn-behavior-'));
  await mkdir(path.join(root,'android')); await mkdir(path.join(root,'ios'));
  await writeFile(path.join(root,'package.json'),JSON.stringify({name:'BehaviorApp',dependencies:{'react-native':'0.87.1'}}));
  const proposal=await propose(model,root);
  const screen=proposal.files.find(f=>f.path==='src/features/MainPage/MainPageScreen.tsx')!.content;
  const service=proposal.files.find(f=>f.path==='src/data/services/CatalogService.ts')!.content;
  assert.match(screen,/navigation\.navigate\("details"\)/);
  assert.match(screen,/Query is required/);
  assert.match(screen,/\["Id"\]/);
  assert.match(service,/fetch\(url\.toString\(\)/);
  assert.ok(proposal.findings.some(f=>f.code==='NATIVE_INTEGRATION'));
});
test('proposal requires review and protects locally modified files',async () => {
  const model=await analyze(fixture);
  const root=await mkdtemp(path.join(os.tmpdir(),'maui2rn-test-'));
  await mkdir(path.join(root,'android')); await mkdir(path.join(root,'ios'));
  const pkg=JSON.stringify({name:'SampleApp',version:'0.0.1',dependencies:{'react-native':'0.87.1'}});
  await writeFile(path.join(root,'package.json'),pkg);
  await writeFile(path.join(root,'App.tsx'),'template');
  const jestConfig="module.exports = {preset: '@react-native/jest-preset'};\n";
  await writeFile(path.join(root,'jest.config.js'),jestConfig);
  await writeJson(path.join(root,'.maui2rn','bootstrap.json'),{schemaVersion:1,files:{'App.tsx':sha256('template'),'package.json':sha256(pkg),'jest.config.js':sha256(jestConfig)}});
  const proposal=await propose(model,root);
  assert.ok(proposal.files.some(f=>f.path==='src/data/services/CustomerService.ts'));
  assert.ok(proposal.files.some(f=>f.path==='src/domain/nativeIntegrationPlan.json'));
  assert.ok(proposal.files.some(f=>f.path==='src/domain/parityManifest.json'));
  const behaviorModel=structuredClone(model);
  const vm=behaviorModel.classes.find(c=>c.name==='MainPageViewModel')!;
  vm.commands=[{name:'SearchCommand',method:'Search',supported:true,actions:[{kind:'navigate',target:'',value:'home'}]}];
  vm.properties.find(p=>p.name==='Query')!.validation=[{kind:'Required'}];
  const behavior=await propose(behaviorModel,root);
  const behaviorScreen=behavior.files.find(f=>f.path.endsWith('MainPageScreen.tsx'))!.content;
  assert.match(behaviorScreen,/navigation\.navigate\("home"\)/);
  assert.match(behaviorScreen,/Query is required/);
  assert.doesNotMatch(behaviorScreen,/Search \(migration pending\)/);
  const proposalFile=await saveProposal(proposal);
  const review=await reviewProposal(proposalFile);
  const page=await fetch(review.url);
  assert.equal(page.status,200);
  assert.match(await page.text(),/Record complete review/);
  const approve=await fetch(review.url.replace('/?token=','/approve?token='),{method:'POST',headers:{'content-type':'application/json',origin:new URL(review.url).origin},body:JSON.stringify({files:proposal.files.map(f=>f.path)})});
  assert.equal(approve.status,200);
  await assert.rejects(()=>applyProposal(proposalFile),/High-risk/);
  await writeFile(path.join(root,'App.tsx'),'changed before first apply');
  await assert.rejects(()=>applyProposal(proposalFile,{approveHighRisk:true,acceptTemplate:true}),/differs from managed/);
  await writeFile(path.join(root,'App.tsx'),'template');
  const applied=await applyProposal(proposalFile,{reviewReceipt:true,acceptTemplate:true});
  assert.ok(applied.written.includes('App.tsx'));
  const current=await currentFindings(root);
  const firstHigh=current.find(f=>f.severity==='high');
  assert.ok(firstHigh);
  const id=findingId(firstHigh);
  await resolveFinding(root,id,'Implemented command and checked sample behavior');
  assert.ok((await resolutions(root)).some(x=>x.id===id));
  const screen=await readFile(path.join(root,'src','features','MainPage','MainPageScreen.tsx'),'utf8');
  assert.match(screen,/TextInput/);
  assert.match(screen,/FlatList/);
  await writeFile(path.join(root,'App.tsx'),'user edit');
  await assert.rejects(()=>applyProposal(proposalFile,{approveHighRisk:true,acceptTemplate:true}),/differs from managed/);
});
